/**
 * This module is generated by Emscripten with MODULARIZE=1, 
 * so the default export is a factory function returning a Promise.
 * 
 * Usage example:
 * 
 *   import createSolverModule from './solver_js.js';
 *   import type { SolverModule } from './solver.d.ts';
 * 
 *   createSolverModule().then((mod: SolverModule) => {
 *     const solver = new mod.Solver(100);
 *     ...
 *   });
 */

/**
 * The Emscripten module factory for the 'solver_js.js' code.
 * Produces an object containing all exports, including the `Solver` class.
 */
declare function createSolverModule(): Promise<SolverModule>;

/**
 * A generic interface for Embind vectors.
 * Note: These types are not plain arrays, they are objects with methods like push_back.
 */
export interface EmbindVector<T> {
  push_back(item: T): void;
  resize(newSize: number, defaultValue: T): void;
  size(): number;
  get(index: number): T;
  set(index: number, value: T): void;
}

/**
 * Registered vector types from Embind.
 */
export interface VectorDouble extends EmbindVector<number> {}
export interface VectorFloat extends EmbindVector<number> {}
export interface VectorString extends EmbindVector<string> {}
export interface VectorOfVectorDouble extends EmbindVector<VectorDouble> {}

/**
 * The shape of the module returned by `createSolverModule()`.
 * It exposes a `Solver` class and the vector constructors.
 */
export interface SolverModule {
  /**
   * The Solver class from the WASM build.
   */
  Solver: {
    /**
     * Constructs a new Solver with an optional LRU cache size.
     * @param exprCacheSize The maximum number of entries the expression cache can hold (default 100).
     */
    new (exprCacheSize?: number): SolverInstance;
  };
  /**
   * Constructor for a vector of doubles.
   */
  VectorDouble: {
    new (): VectorDouble;
  };
  /**
   * Constructor for a vector of floats.
   */
  VectorFloat: {
    new (): VectorFloat;
  };
  /**
   * Constructor for a vector of strings.
   */
  VectorString: {
    new (): VectorString;
  };
  /**
   * Constructor for a vector of vectors of doubles.
   */
  VectorOfVectorDouble: {
    new (): VectorOfVectorDouble;
  };
  // Allow any additional properties.
  [x: string]: any;
}

/**
 * Represents an instance of the Solver class in JavaScript.
 * This matches the C++ methods you bound in your Embind code.
 */
export interface SolverInstance {
  /**
   * Declares a constant in the solver's symbol table.
   * @param name The name of the constant.
   * @param value The numeric value of the constant.
   */
  declare_constant(name: string, value: number): void;

  /**
   * Declares (or re-declares) a variable in the solver's symbol table.
   * @param name The name of the variable.
   * @param value The numeric value to assign to the variable.
   */
  declare_variable(name: string, value: number): void;

  /**
   * Declares a user-defined function in terms of an expression and parameter list.
   * @param name The function name (e.g. "f").
   * @param args A vector of parameter names (use mod.VectorString).
   * @param expression The expression defining the function body (e.g. "x^2 + y^2").
   */
  declare_function(name: string, args: VectorString, expression: string): void;

  /**
   * Evaluates a mathematical expression and returns its numeric result.
   * @param expression A string representing the mathematical expression to evaluate.
   * @param debug Whether to enable debug output (default false).
   */
  evaluate(expression: string, debug?: boolean): number;

  /**
   * Evaluates a mathematical expression for each value in a range of inputs for one variable.
   * @param variable The name of the variable, e.g. "x".
   * @param values A vector of numeric values (use mod.VectorDouble) to assign to that variable.
   * @param expression The expression to evaluate, e.g. "x^2 + 1".
   * @param debug Optional debug flag.
   * @returns A vector of results, one per input value.
   */
  evaluate_range(variable: string, values: VectorDouble, expression: string, debug?: boolean): VectorDouble;

  /**
   * Evaluates a single expression across multiple variables, each with a range of values.
   * @param variables A vector of variable names (use mod.VectorString), e.g. ["x", "y"].
   * @param valuesSets A vector of vectors of numeric values (use mod.VectorOfVectorDouble) for each variable.
   * @param expression The expression to evaluate, e.g. "x+y".
   * @param debug Optional debug flag.
   * @returns A flat vector of results of size = product of each value set length.
   */
  evaluate_ranges(
    variables: VectorString,
    valuesSets: VectorOfVectorDouble,
    expression: string,
    debug?: boolean
  ): VectorDouble;

  /**
   * Clears the solver's expression cache and function cache.
   */
  clear_cache(): void;

  /**
   * Toggles whether the solver uses its LRU cache.
   * @param useCache True to enable caching, false to disable.
   */
  use_cache(useCache: boolean): void;
}

/**
 * Export the default factory function so TypeScript recognizes the usage:
 * 
 *   import createSolverModule from './solver_js.js';
 */
export default createSolverModule;
