/**
 * This module is generated by Emscripten with MODULARIZE=1, 
 * so the default export is a factory function returning a Promise.
 * 
 * Usage example:
 * 
 *   import createSolverModule from './solver_js.js';
 *   import type { SolverModule } from './solver.d.ts';
 * 
 *   createSolverModule().then((mod: SolverModule) => {
 *     const solver = new mod.Solver(100);
 *     ...
 *   });
 */

/**
 * The Emscripten module factory for the 'solver_js.js' code.
 * Produces an object containing all exports, including the `Solver` class.
 */
declare function createSolverModule(): Promise<SolverModule>;

/**
 * The shape of the module returned by `createSolverModule()`.
 * It exposes a `Solver` class that we can instantiate and use.
 */
export interface SolverModule {
  /**
   * The Solver class from the WASM build.
   */
  Solver: {
    /**
     * Constructs a new Solver with an optional LRU cache size.
     * @param exprCacheSize The maximum number of entries the expression cache can hold (default 100).
     */
    new(exprCacheSize?: number): SolverInstance;
  };
}

/**
 * Represents an instance of the Solver class in JavaScript.
 * This matches the C++ methods you bound in your Embind code.
 */
export interface SolverInstance {
  /**
   * Declares a constant in the solver's symbol table.
   * @param name The name of the constant.
   * @param value The numeric value of the constant.
   */
  declare_constant(name: string, value: number): void;

  /**
   * Declares (or re-declares) a variable in the solver's symbol table.
   * @param name The name of the variable.
   * @param value The numeric value to assign to the variable.
   */
  declare_variable(name: string, value: number): void;

  /**
   * @brief Declares a user-defined function in terms of an expression and parameter list.
   * 
   * Internally, this parses the expression to a flattened postfix form and stores it, along
   * with the argument names. When invoked in other expressions, the function is inlined
   * (substituted for its body) or evaluated as needed.
   * 
   * @param name The function name (e.g. "f").
   * @param args A list of parameter names (e.g. ["x", "y"]).
   * @param expression The expression defining the function body (e.g. "x^2 + y^2").
   * @throws SolverException If the function name is invalid, the syntax is incorrect,
   *         or a function by the same name already exists.
   */
  declare_function(name: string, args: string[], expression: string): void;

  /**
   * Evaluates a mathematical expression and returns its numeric result.
   * @param expression A string representing the mathematical expression to evaluate.
   * @param debug Whether to enable debug output (default false).
   */
  evaluate(expression: string, debug?: boolean): number;

  /**
   * Evaluates a mathematical expression for each value in a range of inputs for one variable.
   * @param variable The name of the variable, e.g. "x".
   * @param values A list of numeric values to assign to that variable.
   * @param expression The expression to evaluate, e.g. "x^2 + 1".
   * @param debug Optional debug flag.
   * @returns An array of results, one per input value in `values`.
   */
  evaluate_range(variable: string, values: number[], expression: string, debug?: boolean): number[];

  /**
   * Evaluates a single expression across multiple variables, each with a range of values.
   * @param variables A list of variable names, e.g. ["x", "y"].
   * @param valuesSets An array of arrays of numeric values for each variable.
   * @param expression The expression to evaluate, e.g. "x+y".
   * @param debug Optional debug flag.
   * @returns A flat array of results of size = product of each value set length.
   */
  evaluate_ranges(
    variables: string[],
    valuesSets: number[][],
    expression: string,
    debug?: boolean
  ): number[];

  /**
   * Clears the solver's expression cache and function cache.
   */
  clear_cache(): void;

  /**
   * Toggles whether the solver uses its LRU cache.
   * @param useCache True to enable caching, false to disable.
   */
  use_cache(useCache: boolean): void;

  // ... If you have more methods (declareFunction, etc.), you can add them here:
  // declare_function(...): void;
  // etc.
}

/**
 * Export the default factory function so TypeScript recognizes the usage:
 * 
 *   import createSolverModule from './solver_js.js';
 */
export default createSolverModule;
