name: Build and Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Installation step for Linux
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          echo "Installing dependencies on Linux..."
          sudo apt-get update
          sudo apt-get install -y cmake swig
          
          echo "Setting up virtual environment..."
          python3 -m venv .venv
          source .venv/bin/activate
          pip install numpy matplotlib colorama

      # Installation step for macOS
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          echo "Installing dependencies on macOS..."
          brew install swig

          echo "Setting up virtual environment..."
          python3 -m venv .venv
          source .venv/bin/activate
          pip install numpy matplotlib colorama

      # Installation step for Windows
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          echo "Installing dependencies on Windows..."
          python -m venv .venv
          .venv\Scripts\activate
          pip install numpy matplotlib colorama

      # Build and test step for Linux
      - name: Build and Test on Linux
        if: runner.os == 'Linux'
        run: |
          echo "Running build on Linux..."
          chmod +x build.sh
          ./build.sh build
          
          echo "Running tests on Linux..."
          ./build.sh tests

      # Build and test step for macOS
      - name: Build and Test on macOS
        if: runner.os == 'macOS'
        run: |
          echo "Running build on macOS..."
          chmod +x build.sh
          ./build.sh build

          echo "Running tests on macOS..."
          ./build.sh tests

      # Build and test step for Windows
      - name: Build and Test on Windows
        if: runner.os == 'Windows'
        run: |
          echo "Running build on Windows..."
          cmd /c build.bat build

          echo "Running tests on Windows..."
          cmd /c build.bat tests

      # Ensure test failure stops the job
      - name: Fail on test failure
        if: failure()
        run: |
          echo "A test has failed. Stopping the pipeline."
          exit 1
